# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyEvents' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyEvents

pod 'FBSDKCoreKit', '~> 4.14'
pod 'FBSDKShareKit', '~> 4.14'
pod 'FBSDKLoginKit', '~> 4.14'

  target 'MyEventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyEventsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
